# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taborniki', '0013_remove_oseba_rojstvo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeAkcija', models.CharField(max_length=50)),
                ('porocilo', models.TextField(max_length=10000)),
                ('organizator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taborniki.Oseba')),
                ('udelezenci', models.ManyToManyField(null=True, related_name='akcija_clan', to='taborniki.Oseba')),
            ],
        ),
        migrations.RemoveField(
            model_name='akcije',
            name='organizator',
        ),
        migrations.RemoveField(
            model_name='akcije',
            name='udelezenci',
        ),
        migrations.AlterField(
            model_name='vod',
            name='rod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rodov_vod', to='taborniki.Rod'),
        ),
        migrations.DeleteModel(
            name='Akcije',
        ),
    ]
