# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taborniki', '0015_auto_20180107_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='organizator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taborniki.Oseba'),
        ),
        migrations.AddField(
            model_name='akcija',
            name='udelezenci',
            field=models.ManyToManyField(null=True, related_name='akcija_clan', to='taborniki.Oseba'),
        ),
    ]
