# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taborniki', '0016_auto_20180107_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcija',
            name='konec',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='akcija',
            name='zacetek',
            field=models.DateTimeField(null=True),
        ),
    ]
