# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taborniki', '0019_auto_20180108_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='organizator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taborniki.Oseba'),
        ),
    ]
